# Generated by Django 4.2.15 on 2024-09-05 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("posts", "0002_alter_post_table"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostAccess",
            fields=[
                ("postAccess_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesses",
                        to="posts.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_access",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "PostAccess",
                "unique_together": {("post", "user")},
            },
        ),
    ]
