# Generated by Django 4.2.15 on 2024-09-05 18:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="post",
            table="Post",
        ),
    ]
