# Generated by Django 4.2.15 on 2024-09-05 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFollow",
            fields=[
                ("userFollow_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "followed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="users.userprofile",
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "UserFollow",
                "unique_together": {("follower", "followed")},
            },
        ),
    ]
